#pragma once

#undef TAPPING_TERM
#define TAPPING_TERM 163

#undef DEBOUNCE
#define DEBOUNCE 5

#undef TAPPING_FORCE_HOLD
#define TAPPING_FORCE_HOLD

#undef IGNORE_MOD_TAP_INTERRUPT
#define IGNORE_MOD_TAP_INTERRUPT

#undef PERMISSIVE_HOLD
//#define PERMISSIVE_HOLD //

#undef QMK_KEYS_PER_SCAN
#define QMK_KEYS_PER_SCAN 8
