# uncomment for debugging
# CONSOLE_ENABLE = yes
COMMAND_ENABLE = no
TAP_DANCE_ENABLE = no
DEBOUNCE_TYPE = eager_pr
UNICODE_ENABLE = no
SWAP_HANDS_ENABLE = no
MOUSEKEY_ENABLE  = no
EXTRAKEY_ENABLE  = no
DYNAMIC_MACRO_ENABLE = yes
